// Code generated by tools/package/go_package.py. DO NOT EDIT.

package dcsref

import "embed"

//go:embed all:data
var dataFS embed.FS

// DCSVersion is the DCS version the data was extracted from.
const DCSVersion = "2.9.30.28536"

// Version is the version of the reference-data packages.
const Version = "0.5.0"

// Series names.
const (
	SeriesAircraft       SeriesName = "aircraft"
	SeriesGroundVehicles SeriesName = "ground_vehicles"
	SeriesPersonnel      SeriesName = "personnel"
	SeriesShips          SeriesName = "ships"
	SeriesStructures     SeriesName = "structures"
	SeriesSensors        SeriesName = "sensors"
	SeriesRadios         SeriesName = "radios"
	SeriesDatalink       SeriesName = "datalink"
	SeriesWeapons        SeriesName = "weapons"
	SeriesWarheads       SeriesName = "warheads"
	SeriesWeaponFlight   SeriesName = "weapon_flight"
	SeriesAircraftFlight SeriesName = "aircraft_flight"
	SeriesStores         SeriesName = "stores"
	SeriesRacks          SeriesName = "racks"
	SeriesGunAmmo        SeriesName = "gun_ammo"
	SeriesFuzes          SeriesName = "fuzes"
	SeriesAttributes     SeriesName = "attributes"
	SeriesCountries      SeriesName = "countries"
	SeriesCallsigns      SeriesName = "callsigns"
	SeriesTasks          SeriesName = "tasks"
	SeriesSkills         SeriesName = "skills"
	SeriesFormations     SeriesName = "formations"
	SeriesActions        SeriesName = "actions"
	SeriesOptions        SeriesName = "options"
	SeriesThreats        SeriesName = "threats"
	SeriesLiveries       SeriesName = "liveries"
	SeriesTheatres       SeriesName = "theatres"
	SeriesBeacons        SeriesName = "beacons"
	SeriesNavaids        SeriesName = "navaids"
	SeriesAirbases       SeriesName = "airbases"
)

// SeriesNames lists every series in registry order.
var SeriesNames = []SeriesName{
	SeriesAircraft,
	SeriesGroundVehicles,
	SeriesPersonnel,
	SeriesShips,
	SeriesStructures,
	SeriesSensors,
	SeriesRadios,
	SeriesDatalink,
	SeriesWeapons,
	SeriesWarheads,
	SeriesWeaponFlight,
	SeriesAircraftFlight,
	SeriesStores,
	SeriesRacks,
	SeriesGunAmmo,
	SeriesFuzes,
	SeriesAttributes,
	SeriesCountries,
	SeriesCallsigns,
	SeriesTasks,
	SeriesSkills,
	SeriesFormations,
	SeriesActions,
	SeriesOptions,
	SeriesThreats,
	SeriesLiveries,
	SeriesTheatres,
	SeriesBeacons,
	SeriesNavaids,
	SeriesAirbases,
}

// SeriesKeys is the record field each series is keyed by.
var SeriesKeys = map[SeriesName]string{
	SeriesAircraft:       "id",
	SeriesGroundVehicles: "id",
	SeriesPersonnel:      "id",
	SeriesShips:          "id",
	SeriesStructures:     "id",
	SeriesSensors:        "id",
	SeriesRadios:         "id",
	SeriesDatalink:       "id",
	SeriesWeapons:        "id",
	SeriesWarheads:       "id",
	SeriesWeaponFlight:   "weapon",
	SeriesAircraftFlight: "aircraft",
	SeriesStores:         "clsid",
	SeriesRacks:          "id",
	SeriesGunAmmo:        "id",
	SeriesFuzes:          "id",
	SeriesAttributes:     "id",
	SeriesCountries:      "id",
	SeriesCallsigns:      "country",
	SeriesTasks:          "id",
	SeriesSkills:         "id",
	SeriesFormations:     "id",
	SeriesActions:        "id",
	SeriesOptions:        "id",
	SeriesThreats:        "id",
	SeriesLiveries:       "id",
	SeriesTheatres:       "id",
	SeriesBeacons:        "id",
	SeriesNavaids:        "id",
	SeriesAirbases:       "id",
}

var loadManifest = onceJSON[Provenance]("manifest")

// LoadManifest returns the extraction provenance: DCS version, time,
// modules present.
func LoadManifest() Provenance { return loadManifest() }

var loadAircraft = onceJSON[map[string]Aircraft]("aircraft")

// LoadAircraft returns the aircraft records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadAircraft() map[string]Aircraft { return loadAircraft() }

var loadGroundVehicles = onceJSON[map[string]GroundVehicle]("ground_vehicles")

// LoadGroundVehicles returns the ground_vehicles records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadGroundVehicles() map[string]GroundVehicle { return loadGroundVehicles() }

var loadPersonnel = onceJSON[map[string]Personnel]("personnel")

// LoadPersonnel returns the personnel records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadPersonnel() map[string]Personnel { return loadPersonnel() }

var loadShips = onceJSON[map[string]Ship]("ships")

// LoadShips returns the ships records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadShips() map[string]Ship { return loadShips() }

var loadStructures = onceJSON[map[string]Structure]("structures")

// LoadStructures returns the structures records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadStructures() map[string]Structure { return loadStructures() }

var loadSensors = onceJSON[map[string]Sensor]("sensors")

// LoadSensors returns the sensors records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadSensors() map[string]Sensor { return loadSensors() }

var loadRadios = onceJSON[map[string]Radio]("radios")

// LoadRadios returns the radios records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadRadios() map[string]Radio { return loadRadios() }

var loadDatalink = onceJSON[map[string]Datalink]("datalink")

// LoadDatalink returns the datalink records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadDatalink() map[string]Datalink { return loadDatalink() }

var loadWeapons = onceJSON[map[string]Weapon]("weapons")

// LoadWeapons returns the weapons records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadWeapons() map[string]Weapon { return loadWeapons() }

var loadWarheads = onceJSON[map[string]Warhead]("warheads")

// LoadWarheads returns the warheads records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadWarheads() map[string]Warhead { return loadWarheads() }

var loadWeaponFlight = onceJSON[map[string]WeaponFlight]("weapon_flight")

// LoadWeaponFlight returns the weapon_flight records keyed by weapon, decoded on
// first call. The map is shared: do not modify it.
func LoadWeaponFlight() map[string]WeaponFlight { return loadWeaponFlight() }

var loadAircraftFlight = onceJSON[map[string]AircraftFlight]("aircraft_flight")

// LoadAircraftFlight returns the aircraft_flight records keyed by aircraft, decoded on
// first call. The map is shared: do not modify it.
func LoadAircraftFlight() map[string]AircraftFlight { return loadAircraftFlight() }

var loadStores = onceJSON[map[string]Store]("stores")

// LoadStores returns the stores records keyed by clsid, decoded on
// first call. The map is shared: do not modify it.
func LoadStores() map[string]Store { return loadStores() }

var loadRacks = onceJSON[map[string]Rack]("racks")

// LoadRacks returns the racks records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadRacks() map[string]Rack { return loadRacks() }

var loadGunAmmo = onceJSON[map[string]GunAmmo]("gun_ammo")

// LoadGunAmmo returns the gun_ammo records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadGunAmmo() map[string]GunAmmo { return loadGunAmmo() }

var loadFuzes = onceJSON[map[string]FuzeType]("fuzes")

// LoadFuzes returns the fuzes records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadFuzes() map[string]FuzeType { return loadFuzes() }

var loadAttributes = onceJSON[map[string]Attribute]("attributes")

// LoadAttributes returns the attributes records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadAttributes() map[string]Attribute { return loadAttributes() }

var loadCountries = onceJSON[map[string]Country]("countries")

// LoadCountries returns the countries records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadCountries() map[string]Country { return loadCountries() }

var loadCallsigns = onceJSON[map[string]CountryCallsigns]("callsigns")

// LoadCallsigns returns the callsigns records keyed by country, decoded on
// first call. The map is shared: do not modify it.
func LoadCallsigns() map[string]CountryCallsigns { return loadCallsigns() }

var loadTasks = onceJSON[map[string]Task]("tasks")

// LoadTasks returns the tasks records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadTasks() map[string]Task { return loadTasks() }

var loadSkills = onceJSON[map[string]Skill]("skills")

// LoadSkills returns the skills records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadSkills() map[string]Skill { return loadSkills() }

var loadFormations = onceJSON[map[string]Formation]("formations")

// LoadFormations returns the formations records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadFormations() map[string]Formation { return loadFormations() }

var loadActions = onceJSON[map[string]Action]("actions")

// LoadActions returns the actions records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadActions() map[string]Action { return loadActions() }

var loadOptions = onceJSON[map[string]ActionOption]("options")

// LoadOptions returns the options records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadOptions() map[string]ActionOption { return loadOptions() }

var loadThreats = onceJSON[map[string]ThreatSystem]("threats")

// LoadThreats returns the threats records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadThreats() map[string]ThreatSystem { return loadThreats() }

var loadLiveries = onceJSON[map[string]Livery]("liveries")

// LoadLiveries returns the liveries records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadLiveries() map[string]Livery { return loadLiveries() }

var loadTheatres = onceJSON[map[string]Theatre]("theatres")

// LoadTheatres returns the theatres records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadTheatres() map[string]Theatre { return loadTheatres() }

var loadBeacons = onceJSON[map[string]Beacon]("beacons")

// LoadBeacons returns the beacons records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadBeacons() map[string]Beacon { return loadBeacons() }

var loadNavaids = onceJSON[map[string]Navaid]("navaids")

// LoadNavaids returns the navaids records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadNavaids() map[string]Navaid { return loadNavaids() }

var loadAirbases = onceJSON[map[string]Airbase]("airbases")

// LoadAirbases returns the airbases records keyed by id, decoded on
// first call. The map is shared: do not modify it.
func LoadAirbases() map[string]Airbase { return loadAirbases() }
