// Code generated by tools/package/go_package.py. DO NOT EDIT.

package dcsref

// strictSeries decodes each series with unknown fields rejected.
var strictSeries = map[SeriesName]func([]byte) (map[string]any, error){
	SeriesAircraft:       strictDecode[Aircraft],
	SeriesGroundVehicles: strictDecode[GroundVehicle],
	SeriesPersonnel:      strictDecode[Personnel],
	SeriesShips:          strictDecode[Ship],
	SeriesStructures:     strictDecode[Structure],
	SeriesSensors:        strictDecode[Sensor],
	SeriesRadios:         strictDecode[Radio],
	SeriesDatalink:       strictDecode[Datalink],
	SeriesWeapons:        strictDecode[Weapon],
	SeriesWarheads:       strictDecode[Warhead],
	SeriesStores:         strictDecode[Store],
	SeriesRacks:          strictDecode[Rack],
	SeriesGunAmmo:        strictDecode[GunAmmo],
	SeriesFuzes:          strictDecode[FuzeType],
	SeriesAttributes:     strictDecode[Attribute],
	SeriesCountries:      strictDecode[Country],
	SeriesCallsigns:      strictDecode[CountryCallsigns],
	SeriesTasks:          strictDecode[Task],
	SeriesSkills:         strictDecode[Skill],
	SeriesFormations:     strictDecode[Formation],
	SeriesActions:        strictDecode[Action],
	SeriesOptions:        strictDecode[ActionOption],
	SeriesThreats:        strictDecode[ThreatSystem],
	SeriesLiveries:       strictDecode[Livery],
	SeriesTheatres:       strictDecode[Theatre],
	SeriesBeacons:        strictDecode[Beacon],
	SeriesNavaids:        strictDecode[Navaid],
	SeriesAirbases:       strictDecode[Airbase],
}

// seriesLen counts the records each loader returns.
var seriesLen = func(name SeriesName) int {
	switch name {
	case SeriesAircraft:
		return len(LoadAircraft())
	case SeriesGroundVehicles:
		return len(LoadGroundVehicles())
	case SeriesPersonnel:
		return len(LoadPersonnel())
	case SeriesShips:
		return len(LoadShips())
	case SeriesStructures:
		return len(LoadStructures())
	case SeriesSensors:
		return len(LoadSensors())
	case SeriesRadios:
		return len(LoadRadios())
	case SeriesDatalink:
		return len(LoadDatalink())
	case SeriesWeapons:
		return len(LoadWeapons())
	case SeriesWarheads:
		return len(LoadWarheads())
	case SeriesStores:
		return len(LoadStores())
	case SeriesRacks:
		return len(LoadRacks())
	case SeriesGunAmmo:
		return len(LoadGunAmmo())
	case SeriesFuzes:
		return len(LoadFuzes())
	case SeriesAttributes:
		return len(LoadAttributes())
	case SeriesCountries:
		return len(LoadCountries())
	case SeriesCallsigns:
		return len(LoadCallsigns())
	case SeriesTasks:
		return len(LoadTasks())
	case SeriesSkills:
		return len(LoadSkills())
	case SeriesFormations:
		return len(LoadFormations())
	case SeriesActions:
		return len(LoadActions())
	case SeriesOptions:
		return len(LoadOptions())
	case SeriesThreats:
		return len(LoadThreats())
	case SeriesLiveries:
		return len(LoadLiveries())
	case SeriesTheatres:
		return len(LoadTheatres())
	case SeriesBeacons:
		return len(LoadBeacons())
	case SeriesNavaids:
		return len(LoadNavaids())
	case SeriesAirbases:
		return len(LoadAirbases())
	}
	return -1
}

var strictManifest = strictDecodeOne[Provenance]
