globals: {}

types:
  TaskAttackMapObject:
    kind: record
    description: "Assigns the nearest world object to the point for AI to attack."
    fields:
      id:
        type: string
        description: "Task identifier, must be 'AttackMapObject'"
      params:
        type: TaskAttackMapObjectParams
    required: [id, params]
    
  TaskAttackMapObjectParams:
    kind: record
    description: "Parameters for the AttackMapObject task"
    fields:
      point:
        type: Vec2
        description: "Vec2 coordinate of the target point"
      x:
        type: number
        description: "X coordinate of the target (alternative to point)"
      y:
        type: number
        description: "Y coordinate of the target (alternative to point)"
      weaponType:
        type: number
        description: "Weapon flag type to use for the attack"
      expend:
        type: string
        description: "Quantity of weapons to expend (QUARTER, TWO, ONE, FOUR, HALF, ALL)"
      attackQty:
        type: number
        description: "Number of times the group will attack if the target"
      attackQtyLimit:
        type: boolean
        description: "If true the attackQty value will be followed"
      direction:
        type: number
        description: "Attack direction in radians"
      groupAttack:
        type: boolean
        description: "If true then each aircraft in the group will attack the target"
    required: [point] 