globals: {}

types:
  TaskBombing:
    kind: record
    description: "Assigns a point on the ground for which the AI will attack. Best used for discriminant carpet bombing of a target or having a GBU hit a specific point on the map."
    fields:
      id:
        type: string
        description: "Task identifier, must be 'Bombing'"
      params:
        type: TaskBombingParams
    required: [id, params]
    
  TaskBombingParams:
    kind: record
    description: "Parameters for the Bombing task"
    fields:
      point:
        type: Vec2
        description: "Vec2 coordinate of the target"
      x:
        type: number
        description: "X coordinate of the target (alternative to point)"
      y:
        type: number
        description: "Y coordinate of the target (alternative to point)"
      weaponType:
        type: number
        description: "Weapon flag type to use for the attack"
      expend:
        type: string
        description: "Quantity of weapons to expend (QUARTER, TWO, ONE, FOUR, HALF, ALL)"
      attackQty:
        type: number
        description: "Number of times the group will attack the target"
      attackQtyLimit:
        type: boolean
        description: "Whether to use the attackQty parameter"
      direction:
        type: number
        description: "Attack direction in radians"
      groupAttack:
        type: boolean
        description: "If true then each aircraft in the group will attack the point"
      altitude:
        type: number
        description: "Altitude in meters for the attack"
      altitudeEnabled:
        type: boolean
        description: "Whether to use the altitude parameter"
      attackType:
        type: string
        description: "Attack profile to use (e.g. 'Dive' for dive bombing)"
    required: [point] 