"""Generate the reference-data packages from ``dcs-world-reference/latest/``.

Bundles every series (``tools.package.bundles``) into ``dist/reference/`` with
reverse and name indexes in ``dist/reference/_index/`` (``tools.package.indexes``), then
writes the generated parts of each package (gitignored): record types from the
entity JSON Schema (``tools.package.entity_types``), per-series loaders, the
bundles as package data, and for Lua the bundles as Lua tables zipped into
``dist/``. The TypeScript and Python package versions are set from ``VERSION``
and their DCS version from the reference data manifest (``dcsVersion``).
Compiling and packing is left to ``tsc``/``npm pack`` and ``uv build``
(``task package``).

    uv run python -m tools.package.build
"""

from __future__ import annotations

import io
import json
import re
import tomllib
import zipfile
from pathlib import Path
from typing import Any

from tools.datamine.common import (
    DIST_DIR,
    JSON_SCHEMA_PATH,
    LATEST,
    MANIFEST_TYPE,
    REFERENCE_DATA_DIR,
    REPO_ROOT,
    SERIES,
    SPEC_PATH,
    fail,
    load_json,
    sync_tree,
    write_bytes_if_changed,
    write_text_if_changed,
)

from . import bundles, entity_types, indexes, rules, tables
from .lua_data import lua_bundle, lua_module

PACKAGES = REPO_ROOT / "packages"
TS_DIR = PACKAGES / "typescript"
PY_DIR = PACKAGES / "python"
PY_PKG = PY_DIR / "src" / "dcs_world_reference"
LUA_DIR = PACKAGES / "lua"
LUA_PKG = LUA_DIR / "dcs_world_reference"
GENERATED = "Generated by tools/package/build.py; do not edit."
# The public names of packages/python/src/dcs_world_reference/lookup.py.
PY_LOOKUP = [
    "Reference",
    "aircraft_carrying",
    "airbase_by_name",
    "find_by_name",
    "name_key",
    "references_to",
    "stores_delivering",
    "threats_for_unit",
]
# The public names of packages/python/src/dcs_world_reference/helpers.py.
PY_HELPERS = [
    "BestRunway",
    "CoordFormat",
    "DatalinkCapability",
    "DistanceBearing",
    "EARTH_RADIUS_M",
    "FREQUENCY_TOLERANCE_MHZ",
    "FitConflict",
    "FitResult",
    "FrequencyCheck",
    "FrequencyRange",
    "LatLon",
    "LaunchPlatforms",
    "LoadoutMass",
    "MapXZ",
    "NM_M",
    "NearbyAirbase",
    "ParsedCoord",
    "RadioBands",
    "RunwayEnd",
    "RunwayThreshold",
    "SensorSummary",
    "TacanBand",
    "TacanChannel",
    "TacanFrequency",
    "ThreatRange",
    "UnitDetectionInfo",
    "WIND_TOLERANCE_KT",
    "WarheadInfo",
    "WeaponInfo",
    "aircraft_roles",
    "best_runway",
    "can_mount",
    "country_id",
    "country_name",
    "datalink_capability",
    "destination",
    "distance_bearing",
    "fit_stores",
    "format_coord",
    "is_valid_frequency",
    "is_valid_tacan",
    "launch_platforms",
    "liveries_for",
    "loadout_mass",
    "model_to_units",
    "navaids_for",
    "nearest_airbases",
    "parse_coord",
    "radio_bands",
    "runway_ends",
    "stands_for",
    "stations_accepting",
    "tacan_channel",
    "tacan_frequency",
    "theatre_by_name",
    "threat_for_unit_type",
    "threat_range",
    "threat_ring_geojson",
    "to_lat_lon",
    "to_map_xz",
    "unit_class",
    "unit_detection",
    "weapon_info",
]


def camel(name: str) -> str:
    head, *rest = name.split("_")
    return head + "".join(p.capitalize() for p in rest)


def sync_dir(directory: Path, files: dict[str, str]) -> None:
    """Make ``directory`` hold exactly ``files`` (name -> text); unchanged
    files are not rewritten."""
    sync_tree(directory, {directory / n: t.encode("utf-8") for n, t in files.items()})


def series_types() -> list[tuple[str, str]]:
    """(series, record type name) in registry order."""
    return [(s.name, entity_types.type_name(s.type_name)) for s in SERIES.values()]


def series_keys() -> dict[str, str]:
    """The field each series' bundle is keyed by."""
    return {n: s.id_field for n, s in SERIES.items()}


DCS_SUFFIX = re.compile(r" \(DCS [^)]*\)$")
DCS_KEYWORD = re.compile(r"^dcs-\d")


def package_json(text: str, version: str, dcs_version: str) -> str:
    """``package.json`` with ``version`` and ``dcsVersion`` (right after it) set."""
    pkg = json.loads(text)
    out: dict[str, Any] = {}
    for key, value in pkg.items():
        if key == "dcsVersion":
            continue
        out[key] = value
        if key == "version":
            out["version"] = version
            out["dcsVersion"] = dcs_version
    if "version" not in out:
        fail("no version in package.json")
    return json.dumps(out, indent=2) + "\n"


def package_lock(text: str, version: str, _dcs_version: str) -> str:
    """``package-lock.json`` with the root package's ``version`` set (top level
    and ``packages[""]``)."""
    lock = json.loads(text)
    root = lock.get("packages", {}).get("")
    if "version" not in lock or not isinstance(root, dict):
        fail("no version or root package in package-lock.json")
    lock["version"] = version
    root["version"] = version
    return json.dumps(lock, indent=2) + "\n"


def _toml_line(text: str, key: str, value: str) -> str:
    new, n = re.subn(
        rf"^{key} = .*$", lambda _: f"{key} = {value}", text, count=1, flags=re.M
    )
    if n != 1:
        fail(f"no {key} line in pyproject.toml")
    return new


def pyproject(text: str, version: str, dcs_version: str) -> str:
    """``pyproject.toml`` with ``version`` set, the DCS version at the end of
    ``description`` and as the ``dcs-<version>`` keyword."""
    meta = tomllib.loads(text)["project"]
    description = DCS_SUFFIX.sub("", meta["description"]) + f" (DCS {dcs_version})"
    keywords = [k for k in meta.get("keywords", []) if not DCS_KEYWORD.match(k)]
    keywords.append(f"dcs-{dcs_version}")
    text = _toml_line(text, "version", json.dumps(version))
    text = _toml_line(text, "description", json.dumps(description))
    return _toml_line(text, "keywords", json.dumps(keywords))


def sync_versions(version: str, dcs_version: str) -> None:
    """Set the package version (``VERSION``) and the DCS version (reference
    data manifest) in the npm and Python package metadata."""
    for path, update in (
        (TS_DIR / "package.json", package_json),
        (TS_DIR / "package-lock.json", package_lock),
        (PY_DIR / "pyproject.toml", pyproject),
    ):
        text = path.read_text(encoding="utf-8")
        new = update(text, version, dcs_version)
        if new != text:
            write_text_if_changed(path, new)
            print(f"Set {path.relative_to(REPO_ROOT)} to {version} (DCS {dcs_version})")


# TypeScript ---------------------------------------------------------------


def build_typescript(
    defs: list[entity_types.Definition],
    dcs_version: str,
    manifest_type: str,
    data: dict[str, str],
) -> None:
    sync_dir(TS_DIR / "data", data)
    src = {
        "types.ts": entity_types.typescript(defs),
        "json.d.ts": f"// {GENERATED}\n"
        'declare module "*.json" {\n'
        "  const value: unknown;\n"
        "  export default value;\n"
        "}\n",
    }
    pairs = series_types()
    type_names = sorted({t for _, t in pairs} | {manifest_type})
    lines = [
        f"// {GENERATED}",
        f"import type {{ {', '.join(type_names)} }} from './types.js';",
        "",
        "export * from './types.js';",
        "",
        "/** DCS version the data was extracted from. */",
        f"export const dcsVersion = {json.dumps(dcs_version)};",
        "",
        "/** A series: records keyed by id. */",
        "export type Series<T> = Readonly<Record<string, T>>;",
        "",
        "/** Record type of each series. */",
        "export interface SeriesTypes {",
        *(f"  {n}: {t};" for n, t in pairs),
        "}",
        "",
        "export type SeriesName = keyof SeriesTypes;",
        "",
        "export const seriesNames: readonly SeriesName[] = [",
        *(f"  {json.dumps(n)}," for n, _ in pairs),
        "];",
        "",
        "/** The record field each series is keyed by. */",
        "export const seriesKeys: Readonly<Record<SeriesName, string>> = {",
        *(f"  {json.dumps(n)}: {json.dumps(k)}," for n, k in series_keys().items()),
        "};",
        "",
        "/** Load a series bundle (`data/<name>.json`); the import is cached by the runtime. */",
        "export async function loadSeries<S extends SeriesName>(",
        "  name: S,",
        "): Promise<Series<SeriesTypes[S]>> {",
        "  const mod = (await import(`../data/${name}.json`, { with: { type: 'json' } })) as {",
        "    default: Series<SeriesTypes[S]>;",
        "  };",
        "  return mod.default;",
        "}",
        "",
        "/** Extraction provenance: DCS version, time, modules present. */",
        f"export async function loadManifest(): Promise<{manifest_type}> {{",
        "  const mod = await import('../data/manifest.json', { with: { type: 'json' } });",
        f"  return mod.default as {manifest_type};",
        "}",
    ]
    for n, t in pairs:
        lines += [
            "",
            f"/** `{n}` records ({t}) keyed by {SERIES[n].id_field}. */",
            f"export function load{entity_types.pascal(n)}(): Promise<Series<{t}>> {{",
            f"  return loadSeries({json.dumps(n)});",
            "}",
        ]
    lines += ["", "export * from './lookup.js';", "export * from './helpers.js';"]
    src["index.ts"] = "\n".join(lines) + "\n"
    for name in ("lookup.ts", "helpers.ts"):
        src[name] = (TS_DIR / name).read_text(encoding="utf-8")
    for n, t in pairs:
        src[f"{n}.ts"] = "\n".join(
            [
                f"// {GENERATED}",
                f"import data from '../data/{n}.json' with {{ type: 'json' }};",
                f"import type {{ {t} }} from './types.js';",
                "",
                f"/** `{n}` records keyed by {SERIES[n].id_field}. */",
                f"export const {camel(n)} = data as Readonly<Record<string, {t}>>;",
                f"export default {camel(n)};",
                "",
            ]
        )
    sync_dir(TS_DIR / "src", src)
    # Every bundle as an object literal typed as its series: `tsc --strict`
    # then checks each record against the generated types, excess keys included.
    sync_dir(
        TS_DIR / "test" / "generated",
        {
            f"{n}.ts": f"// {GENERATED}\n"
            f"import type {{ {t} }} from 'dcs-world-reference';\n\n"
            f"export const {camel(n)}: Record<string, {t}> = "
            f"{data[f'{n}.json'].rstrip()};\n"
            for n, t in pairs
        },
    )


# Python -------------------------------------------------------------------


def build_python(
    defs: list[entity_types.Definition],
    dcs_version: str,
    manifest_type: str,
    data: dict[str, str],
) -> None:
    sync_dir(PY_PKG / "data", data)
    write_text_if_changed(PY_PKG / "entities.py", entity_types.python(defs))
    pairs = series_types()
    type_names = sorted({t for _, t in pairs} | {manifest_type})
    lines = [
        '"""DCS World reference data as typed dictionaries.',
        "",
        "Each loader returns one series, records keyed by id, read on first call",
        "and cached. Record types are in :mod:`dcs_world_reference.entities`.",
        "",
        GENERATED,
        '"""',
        "",
        "import json",
        "from collections.abc import Mapping",
        "from functools import cache",
        "from importlib.resources import files",
        "from typing import Any, Final, Literal, cast",
        "",
        "from .entities import (",
        *(f"    {t}," for t in type_names),
        ")",
        "",
        f"DCS_VERSION: Final = {json.dumps(dcs_version)}",
        '"""DCS version the data was extracted from."""',
        "",
        "SeriesName = Literal[",
        *(f"    {json.dumps(n)}," for n, _ in pairs),
        "]",
        "",
        "SERIES: Final[tuple[SeriesName, ...]] = (",
        *(f"    {json.dumps(n)}," for n, _ in pairs),
        ")",
        "",
        "SERIES_KEYS: Final[Mapping[SeriesName, str]] = {",
        *(f"    {json.dumps(n)}: {json.dumps(k)}," for n, k in series_keys().items()),
        "}",
        '"""The record field each series is keyed by."""',
        "",
        "",
        "@cache",
        "def _load(name: str) -> Any:",
        '    return json.loads(files(__name__).joinpath("data", f"{name}.json").read_text("utf-8"))',
        "",
        "",
        f"def manifest() -> {manifest_type}:",
        '    """Extraction provenance: DCS version, time, modules present."""',
        f'    return cast({manifest_type}, _load("manifest"))',
    ]
    for n, t in pairs:
        lines += [
            "",
            "",
            f"def {n}() -> Mapping[str, {t}]:",
            f'    """``{n}`` records keyed by {SERIES[n].id_field}."""',
            f"    return cast(Mapping[str, {t}], _load({json.dumps(n)}))",
        ]
    exported = [
        "DCS_VERSION",
        "SERIES",
        "SERIES_KEYS",
        "SeriesName",
        "manifest",
        *type_names,
        *(n for n, _ in pairs),
    ]
    lines += [
        "",
        "",
        "from .lookup import (  # noqa: E402",
        *(f"    {h}," for h in PY_LOOKUP),
        ")",
    ]
    lines += [
        "from .helpers import (  # noqa: E402",
        *(f"    {h}," for h in PY_HELPERS),
        ")",
    ]
    exported += PY_LOOKUP + PY_HELPERS
    lines += ["", "__all__ = [", *(f"    {json.dumps(e)}," for e in exported), "]"]
    write_text_if_changed(PY_PKG / "__init__.py", "\n".join(lines) + "\n")


# Lua ----------------------------------------------------------------------


def build_lua(
    defs: list[entity_types.Definition],
    manifest: dict[str, Any],
    version: str,
    series: dict[str, dict[str, Any]],
    index: dict[str, Any],
) -> Path:
    files = {
        f"{n}.lua": lua_bundle(
            bundle, f"{n}, keyed by {SERIES[n].id_field}. {GENERATED}"
        )
        for n, bundle in series.items()
    }
    files["manifest.lua"] = lua_module(manifest, GENERATED)
    for name, payload in index.items():
        header = f"Index {name}. {GENERATED}"
        flat = all(isinstance(v, list) for v in payload.values())
        files[f"{indexes.INDEX_DIR}_{name}.lua"] = (
            lua_bundle(payload, header) if flat else lua_module(payload, header)
        )
    module = [
        "---The table `init.lua` returns; each series loads on first access.",
        "---@class DcsWorldReference",
        "---@field dcsVersion string DCS version the data was extracted from.",
        f"---@field manifest {MANIFEST_TYPE}",
        *(
            f"---@field {n} table<string, {s.type_name}> Keyed by {s.id_field}."
            for n, s in SERIES.items()
        ),
        "---@field load fun(name: string): table Load (or return the loaded) series `name`.",
        "---@field setDir fun(dir: string?) Directory holding the series files, with a trailing slash; nil loads them with `require`.",
        "---@field referencesTo fun(series: string, id: string): DcsReference[] Records referencing record `id` of `series`.",
        "---@field storesDelivering fun(weaponId: string): string[] Store CLSIDs delivering the weapon.",
        "---@field aircraftCarrying fun(weaponId: string): string[] Aircraft with a station accepting a store that delivers the weapon.",
        "---@field threatsForUnit fun(unitId: string): string[] Threat systems of the unit.",
        "---@field airbaseByName fun(name: string, theatre: string?): string[] Airbase ids by name (case-insensitive), optionally in one theatre.",
        "---@field findByName fun(series: string, name: string): string[] Ids of `series` records by displayName or name (case-insensitive).",
        "---@field nameKey fun(name: string): string The key the name indexes use: trimmed, ASCII-lowercased.",
        "---@field theatreByName fun(name: string): Entity.Theatre? Theatre by id, displayName, directory or alias (case-insensitive).",
        "---@field toMapXZ fun(theatre: string, lat: number, lon: number): DcsMapXZ Map metres of a WGS84 point on the theatre.",
        "---@field toLatLon fun(theatre: string, x: number, z: number): DcsLatLon WGS84 point of map metres on the theatre.",
        "---@field threatRange fun(threatId: string): DcsThreatRange Union of the threat's envelopes and its sensors' reach.",
        "---@field threatForUnitType fun(unitType: string): string[] Threat systems of a unit type (errors for an unknown one).",
        "---@field threatRingGeoJSON fun(threatId: string, lat: number, lon: number, options: { segments: integer? }?): table GeoJSON rings of the threat's range.",
        "---@field EARTH_RADIUS_M number Mean Earth radius of the ring geometry, metres.",
        "---@field aircraftRoles fun(aircraftId: string): string[] Sorted roles from the classification rules.",
        "---@field unitClass fun(unitId: string): string Class from the classification rules, else `other`.",
        "---@field stationsAccepting fun(aircraftId: string, clsid: string): integer[] Stations accepting the store.",
        "---@field canMount fun(aircraftId: string, station: integer, clsid: string): boolean Whether the station accepts the store.",
        "---@field fitStores fun(aircraftId: string, clsids: string[]): DcsFitResult One station per store, lowest first.",
        "---@field loadoutMass fun(aircraftId: string, loadout: table<integer, string>, fuelKg: number?): DcsLoadoutMass Empty + stores + fuel.",
        "---@field radioBands fun(aircraftId: string): DcsRadioBands[] The aircraft's radios by index.",
        "---@field isValidFrequency fun(aircraftId: string, radioIndex: integer, mhz: number): DcsFrequencyCheck Range and step check.",
        "---@field STEP_TOLERANCE number Largest distance from a tuning step, in steps, still on the grid.",
        "---@field weaponInfo fun(idOrClsid: string): DcsWeaponInfo The weapon record (by id, or a store delivering one weapon type) with its warhead.",
        "---@field launchPlatforms fun(weaponId: string): DcsLaunchPlatforms Aircraft, ground vehicles and ships launching the weapon.",
        "---@field modelToUnits fun(shape: string): string[] Unit ids whose model.shape is `shape` (case-insensitive).",
        "---@field unitDetection fun(unitId: string): DcsUnitDetection The unit's detection fields and sensors.",
        "---@field tacanFrequency fun(channel: integer, band: 'X'|'Y', role: 'air'|'ground'): DcsTacanFrequency Channel frequencies for the airborne or ground side.",
        "---@field tacanChannel fun(mhz: number, role: 'air'|'ground'|'vhf'): DcsTacanChannel[] Channels on a frequency.",
        "---@field isValidTacan fun(channel: number, band: string): boolean Whether the channel and band exist.",
        "---@field FREQUENCY_TOLERANCE_MHZ number Largest difference, MHz, tacanChannel counts a match.",
        "---@field navaidsFor fun(airbaseId: string, runway: string?): string[] Navaid ids of the airbase or one runway end.",
        "---@field runwayEnds fun(airbaseId: string): DcsRunwayEnd[] Every runway end of the airbase.",
        "---@field bestRunway fun(airbaseId: string, windFromDegTrue: number, windKt: number): DcsBestRunway The end facing the wind.",
        "---@field WIND_TOLERANCE_KT number Wind components closer than this compare equal in bestRunway.",
        "---@field nearestAirbases fun(theatre: string, lat: number, lon: number, options: { minRunwayM: number?, n: integer?, category: string? }?): DcsNearbyAirbase[] Nearest airbases, nearest first.",
        "---@field NM_M number Metres per nautical mile.",
        "---@field standsFor fun(airbaseId: string, aircraftId: string): integer[] termIndex of the stands taking the aircraft.",
        "---@field countryId fun(nameOrAlias: string): integer? Country id by name, short name, constant name or alias.",
        "---@field countryName fun(countryId: integer): string DCS name of the country.",
        "---@field liveriesFor fun(unitType: string, countryId: integer?): string[] Livery ids of the unit type, optionally for a country (all of them for the CJTF countries).",
        "---@field datalinkCapability fun(aircraftId: string): DcsDatalinkCapability? The aircraft's datalink record, if any.",
        "---@field distanceBearing fun(lat1: number, lon1: number, lat2: number, lon2: number): DcsDistanceBearing Great-circle distance and initial bearing.",
        "---@field destination fun(lat: number, lon: number, bearingDeg: number, distM: number): DcsLatLon Point at a distance along a bearing.",
        "---@field formatCoord fun(lat: number, lon: number, fmt: 'DD'|'DMS'|'DDM'|'MGRS', precision: integer?): string A coordinate as the mission editor writes it.",
        "---@field parseCoord fun(text: string): DcsParsedCoord A coordinate in any mission editor copy format.",
        "",
        "---@class DcsWeaponInfo: Entity.Weapon",
        "---@field warhead Entity.Warhead?",
        "",
        "---@class DcsLaunchPlatforms",
        "---@field aircraft string[]",
        "---@field groundVehicles string[]",
        "---@field ships string[]",
        "",
        "---@class DcsSensorSummary",
        "---@field id string",
        "---@field kind string",
        "---@field detectionRangeKm number?",
        "",
        "---@class DcsUnitDetection: Entity.UnitDetection",
        "---@field sensors DcsSensorSummary[]",
        "",
        "---@class DcsTacanFrequency",
        "---@field txMHz number Transmit frequency of the side `role` names.",
        "---@field rxMHz number Receive frequency of that side.",
        "---@field pairedVhfMHz number? VOR/ILS frequency the channel pairs with.",
        "",
        "---@class DcsTacanChannel",
        "---@field channel integer",
        "---@field band 'X'|'Y'",
        "",
        "---@class DcsRunwayThreshold",
        "---@field lat number",
        "---@field lon number",
        "---@field elevationM number",
        "",
        "---@class DcsRunwayEnd",
        "---@field runway string Designator pair of the runway.",
        "---@field designator string",
        "---@field name string DCS's own name of the end.",
        "---@field trueDeg number",
        "---@field magDeg number",
        "---@field threshold DcsRunwayThreshold",
        "---@field lengthM number",
        "",
        "---@class DcsBestRunway",
        "---@field end DcsRunwayEnd",
        "---@field headwindKt number Negative for a tailwind.",
        "---@field crosswindKt number Magnitude.",
        "",
        "---@class DcsNearbyAirbase",
        "---@field id string",
        "---@field distNm number",
        "---@field bearingDeg number",
        "",
        "---@class DcsDatalinkCapability",
        "---@field datalinkType string",
        "---@field canBeLink16Donor boolean",
        "---@field supportsTeamMembers boolean",
        "---@field supportsCrossFlightTeam boolean",
        "---@field maxDonors number",
        "---@field maxTeamMembers number",
        "---@field notes string?",
        "",
        "---@class DcsDistanceBearing",
        "---@field distM number",
        "---@field bearingDeg number Initial true bearing, [0, 360).",
        "",
        "---@class DcsParsedCoord",
        "---@field format 'DD'|'DMS'|'DDM'|'MGRS'|'METRIC'",
        "---@field lat number?",
        "---@field lon number?",
        "---@field x number? METRIC: map metres north.",
        "---@field z number? METRIC: map metres east.",
        "",
        "---@class DcsLatLon",
        "---@field lat number",
        "---@field lon number",
        "",
        "---@class DcsMapXZ",
        "---@field x number Metres north.",
        "---@field z number Metres east.",
        "",
        "---A limit is present only when every envelope of the threat gives it.",
        "---@class DcsThreatRange",
        "---@field rMinKm number?",
        "---@field rMaxKm number?",
        "---@field hMinM number?",
        "---@field hMaxM number?",
        "---@field detectionKm number?",
        "",
        "---@class DcsFitConflict",
        "---@field index integer Position in the requested list, from 1.",
        "---@field clsid string",
        "---@field reason 'unsupported'|'noFreeStation'|'loadoutRules'",
        "",
        "---@class DcsFitResult",
        "---@field assignment table<integer, string>? Station -> CLSID, when every store fits.",
        "---@field conflicts DcsFitConflict[]?",
        "",
        "---@class DcsLoadoutMass",
        "---@field totalKg number",
        "---@field emptyKg number",
        "---@field storesKg number",
        "---@field fuelKg number",
        "---@field maxTakeoffKg number?",
        "---@field overMtow boolean?",
        "",
        "---@class DcsFrequencyRange",
        "---@field minMHz number",
        "---@field maxMHz number",
        "---@field modulations string[] DCS `MODULATION_*` names.",
        "",
        "---@class DcsRadioBands",
        "---@field index integer `<index>` of the radio id `<aircraft>__radio<index>`, from 0.",
        "---@field id string",
        "---@field band string",
        "---@field ranges DcsFrequencyRange[]",
        "---@field presets integer",
        "---@field guard boolean",
        "---@field stepKHz number?",
        "",
        "---@class DcsFrequencyCheck",
        "---@field ok boolean",
        "---@field reason 'outOfRange'|'offStep'|nil",
        "",
        "---A record referencing another: its series, id and the referencing field.",
        "---@class DcsReference",
        "---@field series string",
        "---@field id string",
        "---@field path string Field path from the record, arrays as `[]`.",
        "",
    ]
    files["annotations.lua"] = entity_types.emmylua(defs) + "\n".join(module)
    for stale in LUA_PKG.glob("*.lua"):
        if stale.name != "init.lua" and stale.name not in files:
            stale.unlink()
    for name, text in files.items():
        write_text_if_changed(LUA_PKG / name, text)
    return zip_lua(version, manifest["dcsVersion"])


def lua_zip_name(version: str, dcs_version: str) -> str:
    return f"dcs-world-reference-lua-{version}-dcs{dcs_version}.zip"


def zip_lua(version: str, dcs_version: str) -> Path:
    """``dist/dcs-world-reference-lua-<version>-dcs<dcs version>.zip``, stable
    bytes for stable input."""
    out = DIST_DIR / lua_zip_name(version, dcs_version)
    files = [*sorted(LUA_PKG.glob("*.lua")), LUA_DIR / "README.md"]
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
        for path in files:
            arc = path.relative_to(LUA_DIR).as_posix()
            info = zipfile.ZipInfo(arc, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            zf.writestr(info, path.read_bytes())
    write_bytes_if_changed(out, buf.getvalue())
    return out


def main() -> int:
    version = (REPO_ROOT / "VERSION").read_text(encoding="utf-8").strip()
    for required in (SPEC_PATH, JSON_SCHEMA_PATH):
        if not required.is_file():
            fail(f"{required} missing; run `task build:jsonschema` first")
    bundled = bundles.build(REFERENCE_DATA_DIR / LATEST, bundles.BUNDLE_DIR)
    total = sum(len(b) for b in bundled.series.values())
    print(f"Bundled {total} records into {bundles.BUNDLE_DIR}")
    manifest = bundled.manifest
    document = load_json(JSON_SCHEMA_PATH)
    index = indexes.build(bundled.series, document)
    index["classification"], classified = rules.build(
        bundled.series, bundled.manifest["dcsVersion"]
    )
    tabled, tabled_report = tables.build(bundled.series, bundled.manifest["dcsVersion"])
    index.update(tabled)
    for line in [*classified, *tabled_report]:
        print(line)
    index_files = indexes.files(index)
    sync_tree(
        bundles.BUNDLE_DIR / indexes.INDEX_DIR,
        {bundles.BUNDLE_DIR / n: t.encode("utf-8") for n, t in index_files.items()},
    )
    bundled.files.update(index_files)
    print(f"Wrote {len(index)} indexes into {bundles.BUNDLE_DIR / indexes.INDEX_DIR}")
    defs = entity_types.definitions(document, load_json(SPEC_PATH))
    manifest_type = entity_types.type_name(MANIFEST_TYPE)
    dcs_version = manifest["dcsVersion"]
    sync_versions(version, dcs_version)
    build_typescript(defs, dcs_version, manifest_type, bundled.files)
    build_python(defs, dcs_version, manifest_type, bundled.files)
    zipped = build_lua(defs, manifest, version, bundled.series, index)
    print(f"Generated packages/{{typescript,python,lua}}; wrote {zipped}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
