"""Generate the Go package (``packages/go``, package ``dcsref``) from the series
bundles in ``dist/reference/`` and the entity JSON Schema.

Writes the gitignored parts: ``types_gen.go`` (a struct per record type, a
typed constant set per enum), ``series_gen.go`` (``DCSVersion``, the series
names and keys, a lazy loader per series over the embedded bundles),
``series_gen_test.go`` (a strict decoder per series for the tests) and
``data/`` (the bundles and ``_index/`` gzip-compressed as ``<name>.json.gz``,
embedded with ``go:embed``, decompressed on first load). Run after
``tools.package.build`` (``task package``).

Optional fields use ``omitzero``: absent scalars and records are nil pointers,
absent arrays and maps nil, so a record marshals back to the JSON it came from.

    uv run python -m tools.package.go_package
"""

from __future__ import annotations

import gzip
import json
import re
import shutil
import subprocess

from tools.datamine.common import (
    JSON_SCHEMA_PATH,
    MANIFEST_TYPE,
    REPO_ROOT,
    SERIES,
    SPEC_PATH,
    fail,
    load_json,
    sync_tree,
    write_text_if_changed,
)
from tools.spec_types import Array, Map, Primitive, Ref, TypeNode, Union, format_type

from . import bundles, entity_types
from .entity_types import schema_type

GO_DIR = REPO_ROOT / "packages" / "go"
GENERATED = "// Code generated by tools/package/go_package.py. DO NOT EDIT."
# Words spelled in capitals in Go identifiers.
INITIALISMS = {
    w.lower(): w
    for w in (
        "AAA AM AMFM API AS CJTF CLSID DCS DME EWR FM GDR HF HTTP ICAO ICLS ID IDM ILS "
        "IR IRST JSON LLTV NURS OLS PRMG RSBN RWR SADL SAM SS TACAN TV UHF UK UN "
        "URL USA USSR VHF VOR VORTAC"
    ).split()
}
_WORD = re.compile(r"[A-Z]+(?![a-z])|[A-Z]?[a-z]+|\d+")
# typeRef primitive -> Go type of a record field.
GO_PRIMITIVES = {
    "string": "string",
    "number": "float64",
    "boolean": "bool",
    "any": "any",
}


def go_name(name: str) -> str:
    """``beaconId`` / ``gun_ammo`` / ``BEACON_TYPE_VOR`` / ``country.id`` ->
    ``BeaconID`` / ``GunAmmo`` / ``BeaconTypeVOR`` / ``CountryID``."""
    out = []
    for part in re.split(r"[^A-Za-z0-9]+", name):
        words = _WORD.findall(part) if part.upper() != part else [part]
        for w in words:
            lw = w.lower()
            out.append(INITIALISMS.get(lw, lw[:1].upper() + lw[1:]))
    ident = "".join(out)
    if not ident or ident[0].isdigit():
        ident = "X" + ident
    return ident


def type_name(spec_name: str) -> str:
    return go_name(entity_types.type_name(spec_name))


def _comment(doc: str, indent: str = "") -> list[str]:
    return [f"{indent}// {line}".rstrip() for line in doc.splitlines() if doc]


# Primitive -> (Go field and type-name word, Go type, JSON kind) of a
# generated tagged union; members appear in this order.
UNION_MEMBERS = {
    "boolean": ("Bool", "bool", "a boolean"),
    "number": ("Number", "float64", "a number"),
    "string": ("String", "string", "a string"),
}
# Union type names kept from the hand-written package: the default is the
# member words joined by ``Or`` (``NumberOrString``).
UNION_NAMES = {frozenset(UNION_MEMBERS): "Scalar"}
# The first byte of each member's JSON.
_UNION_CASES = {
    "boolean": "c == 't' || c == 'f'",
    "number": "c == '-' || (c >= '0' && c <= '9')",
    "string": "c == '\"'",
}


def union_name(prims: frozenset[str]) -> str:
    """The Go type of a union of JSON primitives (``UNION_MEMBERS`` keys)."""
    if prims in UNION_NAMES:
        return UNION_NAMES[prims]
    return "Or".join(UNION_MEMBERS[p][0] for p in UNION_MEMBERS if p in prims)


def _either(words: list[str], last: str) -> str:
    return ", ".join(words[:-1]) + f" {last} {words[-1]}"


def union_go(prims: frozenset[str]) -> list[str]:
    """A tagged union of ``prims``: one pointer field per member, exactly one
    set; decodes only those JSON kinds and encodes back to the same JSON."""
    name = union_name(prims)
    order = [p for p in UNION_MEMBERS if p in prims]
    if len(order) < 2 or len(order) != len(prims):
        raise ValueError(f"no tagged union of {sorted(prims)}")
    fields = [UNION_MEMBERS[p] for p in order]
    want = _either([k for _, _, k in fields], "or")
    lines = [
        f"// {name} is a value DCS gives as {want}; exactly one of",
        f"// {_either([w for w, _, _ in fields], 'and')} is set.",
        f"type {name} struct {{",
        *(f"\t{w} *{t}" for w, t, _ in fields),
        "}",
        "",
        f"// UnmarshalJSON accepts {want} and rejects any other JSON.",
        f"func (v *{name}) UnmarshalJSON(b []byte) error {{",
        f"\t*v = {name}{{}}",
        "\tt := bytes.TrimSpace(b)",
        "\tif len(t) > 0 {",
        "\t\tswitch c := t[0]; {",
    ]
    for (word, typ, _), prim in zip(fields, order, strict=True):
        var = "x"  # not ``b``, the parameter
        lines += [
            f"\t\tcase {_UNION_CASES[prim]}:",
            f"\t\t\tvar {var} {typ}",
            f"\t\t\tif err := json.Unmarshal(t, &{var}); err == nil {{",
            f"\t\t\t\tv.{word} = &{var}",
            "\t\t\t\treturn nil",
            "\t\t\t}",
        ]
    lines += [
        "\t\t}",
        "\t}",
        f'\treturn fmt.Errorf("dcsref: want {want}, got %s", t)',
        "}",
        "",
        "// MarshalJSON writes the member that is set (null if none is).",
        f"func (v {name}) MarshalJSON() ([]byte, error) {{",
        "\tswitch {",
    ]
    for word, _, _ in fields:
        lines += [f"\tcase v.{word} != nil:", f"\t\treturn json.Marshal(*v.{word})"]
    lines += ["\t}", '\treturn []byte("null"), nil', "}", ""]
    return lines


class Emitter:
    def __init__(self, defs: list[entity_types.Definition]) -> None:
        self.defs = {d.name: d for d in defs}
        self.unions: set[frozenset[str]] = set()

    def _member_kind(self, node: TypeNode) -> str:
        """``number`` / ``int`` / ``string`` / ``boolean`` of a union member;
        an enum member is its base type."""
        if isinstance(node, Ref):
            d = self.defs[node.name]
            if d.kind == "enum":
                return "int" if isinstance(d.values[0][1], int) else "string"
        if isinstance(node, Primitive) and node.name in UNION_MEMBERS:
            return node.name
        raise ValueError(f"unsupported union member {format_type(node)!r}")

    def union(self, node: Union) -> str:
        """A union of numbers (enums included) is ``float64`` (``int`` if all
        are integer enums); any other union of JSON primitives a generated
        tagged union. Records, arrays, maps, ``any`` or null in a union are
        errors."""
        try:
            kinds = {self._member_kind(m) for m in node.members}
        except ValueError as e:
            raise ValueError(f"unsupported union {format_type(node)!r}: {e}") from e
        if kinds <= {"int", "number"}:
            return "float64" if "number" in kinds else "int"
        prims = frozenset("number" if k == "int" else k for k in kinds)
        self.unions.add(prims)
        return union_name(prims)

    def expr(self, node: TypeNode) -> str:
        if isinstance(node, Union):
            return self.union(node)
        if isinstance(node, Ref):
            return type_name(node.name)
        if isinstance(node, Array):
            return "[]" + self.expr(node.item)
        if isinstance(node, Map):
            return "map[string]" + self.expr(node.value)
        if isinstance(node, Primitive) and node.name in GO_PRIMITIVES:
            return GO_PRIMITIVES[node.name]
        raise ValueError(f"unsupported type {format_type(node)!r}")

    def field(self, f: entity_types.Field) -> tuple[str, str, str]:
        """(Go name, type, tag) of a record field."""
        name = "Sources" if f.name == entity_types.SOURCE_FIELD else go_name(f.name)
        typ = self.expr(entity_types.field_type(f))
        opt = ""
        if not f.required:
            opt = ",omitzero"
            if not typ.startswith(("[]", "map[")) and typ != "any":
                typ = "*" + typ
        return name, typ, f'`json:"{f.name}{opt}"`'

    def types(self) -> str:
        body: list[str] = []
        seen: dict[str, str] = {}

        def claim(ident: str, owner: str) -> str:
            if ident in seen:
                fail(f"Go name {ident} of {owner} clashes with {seen[ident]}")
            seen[ident] = owner
            return ident

        for d in self.defs.values():
            name = claim(type_name(d.name), d.name)
            doc = d.doc or f"{name} is `{d.name}`."
            body += _comment(doc)
            if d.kind == "enum":
                base = "int" if isinstance(d.values[0][1], int) else "string"
                body += [f"type {name} {base}", "", "const ("]
                for k, v in d.values:
                    const = go_name(k)
                    if not const.startswith(name):
                        const = name + const
                    claim(const, f"{d.name}.{k}")
                    body.append(f"\t{const} {name} = {json.dumps(v)}")
                body += [")", ""]
                body += _comment(
                    f"{name}Values maps the DCS names of `{d.name}` to their values."
                )
                claim(f"{name}Values", d.name)
                body.append(f"var {name}Values = map[string]{name}{{")
                for k, v in d.values:
                    body.append(f"\t{json.dumps(k)}: {json.dumps(v)},")
                body += ["}", ""]
            elif d.kind == "array":
                assert d.items is not None
                body += [f"type {name} []{self.expr(schema_type(d.items))}", ""]
            else:
                body.append(f"type {name} struct {{")
                names: set[str] = set()
                for f in d.fields:
                    fname, typ, tag = self.field(f)
                    if fname in names:
                        fail(f"field {fname} of {d.name} clashes")
                    names.add(fname)
                    body += _comment(f.doc, "\t")
                    body.append(f"\t{fname} {typ} {tag}")
                body += ["}", ""]
        head = [GENERATED, "", "package dcsref", ""]
        if self.unions:
            head += ["import (", '\t"bytes"', '\t"encoding/json"', '\t"fmt"', ")", ""]
            for prims in sorted(self.unions, key=union_name):
                claim(union_name(prims), "a generated union")
                body += union_go(prims)
        return "\n".join(head + body)


def series_go(dcs_version: str, version: str) -> str:
    manifest = type_name(MANIFEST_TYPE)
    lines = [
        GENERATED,
        "",
        "package dcsref",
        "",
        'import "embed"',
        "",
        "//go:embed all:data",
        "var dataFS embed.FS",
        "",
        "// DCSVersion is the DCS version the data was extracted from.",
        f"const DCSVersion = {json.dumps(dcs_version)}",
        "",
        "// Version is the version of the reference-data packages.",
        f"const Version = {json.dumps(version)}",
        "",
        "// Series names.",
        "const (",
    ]
    for n in SERIES:
        lines.append(f"\tSeries{go_name(n)} SeriesName = {json.dumps(n)}")
    lines += [
        ")",
        "",
        "// SeriesNames lists every series in registry order.",
        "var SeriesNames = []SeriesName{",
        *(f"\tSeries{go_name(n)}," for n in SERIES),
        "}",
        "",
        "// SeriesKeys is the record field each series is keyed by.",
        "var SeriesKeys = map[SeriesName]string{",
        *(
            f"\tSeries{go_name(n)}: {json.dumps(s.id_field)},"
            for n, s in SERIES.items()
        ),
        "}",
        "",
        f'var loadManifest = onceJSON[{manifest}]("manifest")',
        "",
        "// LoadManifest returns the extraction provenance: DCS version, time,",
        "// modules present.",
        f"func LoadManifest() {manifest} {{ return loadManifest() }}",
    ]
    for n, s in SERIES.items():
        g, t = go_name(n), type_name(s.type_name)
        lines += [
            "",
            f"var load{g} = onceJSON[map[string]{t}]({json.dumps(n)})",
            "",
            f"// Load{g} returns the {n} records keyed by {s.id_field}, decoded on",
            "// first call. The map is shared: do not modify it.",
            f"func Load{g}() map[string]{t} {{ return load{g}() }}",
        ]
    return "\n".join(lines) + "\n"


def series_test_go() -> str:
    lines = [
        GENERATED,
        "",
        "package dcsref",
        "",
        "// strictSeries decodes each series with unknown fields rejected.",
        "var strictSeries = map[SeriesName]func([]byte) (map[string]any, error){",
    ]
    for n, s in SERIES.items():
        lines.append(f"\tSeries{go_name(n)}: strictDecode[{type_name(s.type_name)}],")
    lines += [
        "}",
        "",
        "// seriesLen counts the records each loader returns.",
        "var seriesLen = func(name SeriesName) int {",
        "\tswitch name {",
    ]
    for n in SERIES:
        lines += [f"\tcase Series{go_name(n)}:", f"\t\treturn len(Load{go_name(n)}())"]
    lines += [
        "\t}",
        "\treturn -1",
        "}",
        "",
        f"var strictManifest = strictDecodeOne[{type_name(MANIFEST_TYPE)}]",
    ]
    return "\n".join(lines) + "\n"


def gofmt(source: str) -> str:
    """``source`` through ``gofmt`` (Go is required to build the package)."""
    exe = shutil.which("gofmt")
    if exe is None:
        fail("gofmt not found; install Go to build packages/go")
    return subprocess.run(
        [exe], input=source, capture_output=True, text=True, check=True
    ).stdout


def gz(data: bytes) -> bytes:
    """``data`` gzip-compressed reproducibly: no file name, mtime 0."""
    return gzip.compress(data, compresslevel=9, mtime=0)


def main() -> int:
    for required in (SPEC_PATH, JSON_SCHEMA_PATH, bundles.BUNDLE_DIR / "manifest.json"):
        if not required.is_file():
            fail(f"{required} missing; run `task package` first")
    version = (REPO_ROOT / "VERSION").read_text(encoding="utf-8").strip()
    manifest = load_json(bundles.BUNDLE_DIR / "manifest.json")
    defs = entity_types.definitions(load_json(JSON_SCHEMA_PATH), load_json(SPEC_PATH))
    emitter = Emitter(defs)
    write_text_if_changed(GO_DIR / "types_gen.go", gofmt(emitter.types()))
    write_text_if_changed(
        GO_DIR / "series_gen.go", gofmt(series_go(manifest["dcsVersion"], version))
    )
    write_text_if_changed(GO_DIR / "series_gen_test.go", gofmt(series_test_go()))
    data = GO_DIR / "data"
    sync_tree(
        data,
        {
            data / f"{p.relative_to(bundles.BUNDLE_DIR)}.gz": gz(p.read_bytes())
            for p in sorted(bundles.BUNDLE_DIR.rglob("*.json"))
        },
    )
    print(f"Generated {GO_DIR.relative_to(REPO_ROOT)} (DCS {manifest['dcsVersion']})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
